@echo off
@REM echo Activating Virtual Environment...
@REM call venv1\Scripts\activate

echo Running Data Backup...
python src\data\data_backup.py

echo Running Data Procesing...
python src\data\data_processing.py

echo Running Model Training...
python src\model\model.py

@REM echo Running Model Prediction...
@REM python src\model\predict.py

echo Starting FastAPI Server...
start cmd /k "uvicorn src.backend.main:app --host 0.0.0.0 --port $port"

@REM echo Launching Streamlit App...
@REM start cmd /k "streamlit run src\frontend\app.py"

echo All services started successfully!
